# Generated by Django 3.0.5 on 2020-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='appid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='playtime_forever',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='playtime_two_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
