# Generated by Django 3.0.5 on 2020-04-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200430_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='appid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
