# Generated by Django 3.0.5 on 2020-05-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200503_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='key',
            field=models.CharField(default='steam', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
