# Generated by Django 3.0.5 on 2020-05-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20200503_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='games.Store'),
        ),
    ]
